chore: sync with building base
kubebb/components pull request #61
Opened 2023-07-20 06:03 UTC by 0xff-dev

Fix: https://github.com/kubebb/components/issues/56

2023-07-20 06:57 UTC, bjwswang approved these changes

2023-07-20 06:58 UTC, bjwswang requested changes
fix the chart lint

2023-07-20 08:39 UTC, bjwswang approved these changes

2023-07-21 05:29 UTC, Abirdcfly approved these changes

2023-07-21 05:30 UTC, merged